{
  "formatVersion": "1.1",
  "component": {
    "group": "org.crux",
    "module": "crux-game",
    "version": "0.9.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "crux-game-0.9.0.jar",
          "url": "crux-game-0.9.0.jar",
          "size": 8890,
          "sha512": "7c45f240978f9f09422c8f2848a3021f75829633a78e0d5bc99a05687d4c233b1dc21d6a52eb48af59a8a5e0a0119fbd074e71c3baeb300709e59ecc9db9d018",
          "sha256": "dec2ca07592500c890908b8cdef3b6bda2dde5a2859b5a58bd0a00e99e6c943b",
          "sha1": "5a8a0a8083b27464bdd8ce82ab35be0d1430d1d5",
          "md5": "fe3d7720fce439252e897c08209df2af"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.crux",
          "module": "crux-annotations",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "org.crux",
          "module": "crux-system",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "crux-game-0.9.0.jar",
          "url": "crux-game-0.9.0.jar",
          "size": 8890,
          "sha512": "7c45f240978f9f09422c8f2848a3021f75829633a78e0d5bc99a05687d4c233b1dc21d6a52eb48af59a8a5e0a0119fbd074e71c3baeb300709e59ecc9db9d018",
          "sha256": "dec2ca07592500c890908b8cdef3b6bda2dde5a2859b5a58bd0a00e99e6c943b",
          "sha1": "5a8a0a8083b27464bdd8ce82ab35be0d1430d1d5",
          "md5": "fe3d7720fce439252e897c08209df2af"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "crux-game-0.9.0-sources.jar",
          "url": "crux-game-0.9.0-sources.jar",
          "size": 2775,
          "sha512": "771c5630725ef5662e2af70164b3214b75acdf959fd3541a0de127eadf2e1a4d79f417681cabfe1e622df9e074fb7177298e30ba04f14b5b062eba975cbd6dc0",
          "sha256": "749654aa808363ed599ad0194c13bcb1a18bf3432d109cbb39fe61c77fd4ebbb",
          "sha1": "7337d9f1582dae4f0b3c88606f359a535b080193",
          "md5": "5b46020699b0cf8df530f52dd467b92a"
        }
      ]
    }
  ]
}
