{
  "formatVersion": "1.1",
  "component": {
    "group": "org.crux",
    "module": "crux-processor",
    "version": "0.8.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "crux-processor-0.8.1.jar",
          "url": "crux-processor-0.8.1.jar",
          "size": 3058,
          "sha512": "01bcee55fc0c1904feafa87dc5c06d49fe5e3b53f70ab1ab3f31406822f1ec495dc1995a2678b1b225b7b5d505e4cb26d25320abd0ac0952e70b8d876c1d693a",
          "sha256": "a9e869ab1411f1058e20a11f4890a4de54a3dac05cf02ecab6fa45efd42392f6",
          "sha1": "453815c5f7ba7ae7b2dcf67fa4983b3b9ea6d6da",
          "md5": "5f65aea5dc7cc6a843a5fdd27bb0f51c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "crux-processor-0.8.1.jar",
          "url": "crux-processor-0.8.1.jar",
          "size": 3058,
          "sha512": "01bcee55fc0c1904feafa87dc5c06d49fe5e3b53f70ab1ab3f31406822f1ec495dc1995a2678b1b225b7b5d505e4cb26d25320abd0ac0952e70b8d876c1d693a",
          "sha256": "a9e869ab1411f1058e20a11f4890a4de54a3dac05cf02ecab6fa45efd42392f6",
          "sha1": "453815c5f7ba7ae7b2dcf67fa4983b3b9ea6d6da",
          "md5": "5f65aea5dc7cc6a843a5fdd27bb0f51c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "crux-processor-0.8.1-sources.jar",
          "url": "crux-processor-0.8.1-sources.jar",
          "size": 1803,
          "sha512": "f2810859635a129c489f669177d052f56ac32abac49dc66e7a4c47dfbda9e27dcd71e8daeaf66e387c1cf788959d4806bb321e23b92749b3c312365a7f8cadd1",
          "sha256": "0fe86184a9e24d3598dae9fdfd08515f64872f832a94672b0e6d600da4965517",
          "sha1": "d616475428cc44aaa199b10e0c7a073837559165",
          "md5": "41682d41ed4acf14637f56f1dcbbeab2"
        }
      ]
    }
  ]
}
