{
  "formatVersion": "1.1",
  "component": {
    "group": "org.crux",
    "module": "crux-annotations",
    "version": "0.12.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "crux-annotations-0.12.0.jar",
          "url": "crux-annotations-0.12.0.jar",
          "size": 2092,
          "sha512": "c0eecc8065ffaf660b1760014331df247e0c53258f5fc90f456ce02fc9af09b61c7996b8b050968c3b83d40c49f897ca36d03d8ed79537e0d551d3b1a2835f7d",
          "sha256": "9f53e6a030c85e5a586cc03dfb82ff6270a2cf4181009e54c3b06a503f9ff408",
          "sha1": "be709a73af5502e1088726653599cba2785cf499",
          "md5": "60fcf4c91a4bdcbb145c610d24a3e1b7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "crux-annotations-0.12.0.jar",
          "url": "crux-annotations-0.12.0.jar",
          "size": 2092,
          "sha512": "c0eecc8065ffaf660b1760014331df247e0c53258f5fc90f456ce02fc9af09b61c7996b8b050968c3b83d40c49f897ca36d03d8ed79537e0d551d3b1a2835f7d",
          "sha256": "9f53e6a030c85e5a586cc03dfb82ff6270a2cf4181009e54c3b06a503f9ff408",
          "sha1": "be709a73af5502e1088726653599cba2785cf499",
          "md5": "60fcf4c91a4bdcbb145c610d24a3e1b7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "crux-annotations-0.12.0-sources.jar",
          "url": "crux-annotations-0.12.0-sources.jar",
          "size": 1076,
          "sha512": "a12a0b2f92074c2ae8c1f59ce41d2f4091fed04c74ce00ca1eb351b83ff6b692096be475d84f387a620281bdc71ac81bf0814cdb00707dc0a27cbccdb54f273d",
          "sha256": "9df0d5dcfcfd81494b296d1d7776e8a8ebad8ddf60e90e283fd1be9a1adb5cba",
          "sha1": "b80c80d3de37028c2faf7885f38122e93e1a2d7b",
          "md5": "3b68ed0b19b95498e1363411354ee769"
        }
      ]
    }
  ]
}
