{
  "formatVersion": "1.1",
  "component": {
    "group": "org.crux",
    "module": "crux-game",
    "version": "0.12.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "crux-game-0.12.0.jar",
          "url": "crux-game-0.12.0.jar",
          "size": 12445,
          "sha512": "dfb60d4918254e31a099ea4c3be6bfc6c0e81f9c0de33641abbccf5c78ae5696aea0602a2d8a606257a49cb2bc5acbc27fdbeea42259556c91e860adddbca3fa",
          "sha256": "68608ae6a764894e8b51a50706c70db759cf5039329f31dae8a195745b509249",
          "sha1": "756faff12a6567f5a5229d3656b7d9953d683d4a",
          "md5": "a4d1bfede52447fc0695701ddbe4ce0e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.crux",
          "module": "crux-annotations",
          "version": {
            "requires": "0.12.0"
          }
        },
        {
          "group": "org.crux",
          "module": "crux-system",
          "version": {
            "requires": "0.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "crux-game-0.12.0.jar",
          "url": "crux-game-0.12.0.jar",
          "size": 12445,
          "sha512": "dfb60d4918254e31a099ea4c3be6bfc6c0e81f9c0de33641abbccf5c78ae5696aea0602a2d8a606257a49cb2bc5acbc27fdbeea42259556c91e860adddbca3fa",
          "sha256": "68608ae6a764894e8b51a50706c70db759cf5039329f31dae8a195745b509249",
          "sha1": "756faff12a6567f5a5229d3656b7d9953d683d4a",
          "md5": "a4d1bfede52447fc0695701ddbe4ce0e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "crux-game-0.12.0-sources.jar",
          "url": "crux-game-0.12.0-sources.jar",
          "size": 3579,
          "sha512": "bd5d52ba7455f3c0b2f67341f6e0e6f56ff2e2052db3675eddac9f88a631eaafcb20b8e92f55a0c000ccb80d31cd7de2911342eda0b2e521168c003b512a79f1",
          "sha256": "aabe453c416433225a5846dfe52833c4f2ea5b02684d4ffc4c693a8289c51f6b",
          "sha1": "f1eec84c5de0872eb9aefc431403290dddf82efb",
          "md5": "12bb1e0448e6c551ac63f445de1a944a"
        }
      ]
    }
  ]
}
