{
  "formatVersion": "1.1",
  "component": {
    "group": "org.crux",
    "module": "crux-game",
    "version": "0.16.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "crux-game-0.16.0.jar",
          "url": "crux-game-0.16.0.jar",
          "size": 27367,
          "sha512": "ea37155c49184fc6d9515b6714e678e3b0ad65ab7e813eaa578df7437ebbaf35380764d742ec31872fd03809dc04bb801c7a0a4609553b9b1bc3fff052e60687",
          "sha256": "8bb2e3fcc533add470b6ff94d26df1e1323eb94ecf9adc7b8603b13d3f94c761",
          "sha1": "76d57ae14a0f0c57d93d22b149e0e2bde8aef2a0",
          "md5": "f6fad2e819262d2a889f9a5eaba7ea4b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.crux",
          "module": "crux-annotations",
          "version": {
            "requires": "0.16.0"
          }
        },
        {
          "group": "org.crux",
          "module": "crux-system",
          "version": {
            "requires": "0.16.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "crux-game-0.16.0.jar",
          "url": "crux-game-0.16.0.jar",
          "size": 27367,
          "sha512": "ea37155c49184fc6d9515b6714e678e3b0ad65ab7e813eaa578df7437ebbaf35380764d742ec31872fd03809dc04bb801c7a0a4609553b9b1bc3fff052e60687",
          "sha256": "8bb2e3fcc533add470b6ff94d26df1e1323eb94ecf9adc7b8603b13d3f94c761",
          "sha1": "76d57ae14a0f0c57d93d22b149e0e2bde8aef2a0",
          "md5": "f6fad2e819262d2a889f9a5eaba7ea4b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "crux-game-0.16.0-sources.jar",
          "url": "crux-game-0.16.0-sources.jar",
          "size": 7167,
          "sha512": "d7dd8988aaf0071154ae4aa6272c2a369b6d77f067c7f74976c30c53a61f3d35e9c9607cabe8bcf2ca98523436fd84733acb4d0cb2218c77208068a7c12103b6",
          "sha256": "ad408f36471d700dbde858c0d50ae1ffd3bddc8d39011ec4dd8346fa80d05c10",
          "sha1": "ed22a9cace112e032ee36047d10b3a8197759001",
          "md5": "2dfd0091bc8c8c03a312581a6de7a581"
        }
      ]
    }
  ]
}
