{
  "formatVersion": "1.1",
  "component": {
    "group": "org.crux",
    "module": "crux-lib",
    "version": "0.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "crux-lib-0.4.0.jar",
          "url": "crux-lib-0.4.0.jar",
          "size": 17815,
          "sha512": "743695b9df026791e8c881051b9f6453d68ef078b886ccc1bc376444a7cade4c1c5c9fba5499ec37086a4097b3a856abe8384f113f66c5485afcb84be2dd98c6",
          "sha256": "30599539947b675967083ca43624e087fea87fb92118704717ac420523793666",
          "sha1": "57aac2f73610b302fd9dacdcbf5043e84d5a02fd",
          "md5": "940b709c36fea2a21759c84b143bb3e6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "crux-lib-0.4.0.jar",
          "url": "crux-lib-0.4.0.jar",
          "size": 17815,
          "sha512": "743695b9df026791e8c881051b9f6453d68ef078b886ccc1bc376444a7cade4c1c5c9fba5499ec37086a4097b3a856abe8384f113f66c5485afcb84be2dd98c6",
          "sha256": "30599539947b675967083ca43624e087fea87fb92118704717ac420523793666",
          "sha1": "57aac2f73610b302fd9dacdcbf5043e84d5a02fd",
          "md5": "940b709c36fea2a21759c84b143bb3e6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "crux-lib-0.4.0-sources.jar",
          "url": "crux-lib-0.4.0-sources.jar",
          "size": 3728,
          "sha512": "2fe268ca4a5d0083985de076cc39f9b7fbaf61163ffe4f77121a5e2b1764b07d818258d5e2b88b31fed03bb4fc7b67d148eb19107edc5ccb17e97c6e5e538b6a",
          "sha256": "b3b8bc9d310e23cc07bb25edafbe91ff4e4e4ffea91f746b1225d8aea3ea3e8c",
          "sha1": "3b9795d822aed99483ebb7e3b3f908062f50a1aa",
          "md5": "16b86bf3c94abe93bb5cd39bc988a142"
        }
      ]
    }
  ]
}
