{
  "formatVersion": "1.1",
  "component": {
    "group": "org.crux",
    "module": "crux-system",
    "version": "0.8.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "crux-system-0.8.0.jar",
          "url": "crux-system-0.8.0.jar",
          "size": 19195,
          "sha512": "a2041e169b3eff43404014ce0faf67343355ebdcf6105f21caf40d74132a0917be474316583d9cda8b7a8ab27ea2197286f04d838318d7484e2a3e0422c00ecc",
          "sha256": "ca4a4abf4a47e45d688dc3a43da8f228abc16678d22d45969f6996d90ea5ba0b",
          "sha1": "13a2f920744ed8b2d76affa617f9bfc55c66a38c",
          "md5": "6cdc9ca87f3eb4ffd499e77a08e13297"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.crux",
          "module": "crux-annotations",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "crux-system-0.8.0.jar",
          "url": "crux-system-0.8.0.jar",
          "size": 19195,
          "sha512": "a2041e169b3eff43404014ce0faf67343355ebdcf6105f21caf40d74132a0917be474316583d9cda8b7a8ab27ea2197286f04d838318d7484e2a3e0422c00ecc",
          "sha256": "ca4a4abf4a47e45d688dc3a43da8f228abc16678d22d45969f6996d90ea5ba0b",
          "sha1": "13a2f920744ed8b2d76affa617f9bfc55c66a38c",
          "md5": "6cdc9ca87f3eb4ffd499e77a08e13297"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "crux-system-0.8.0-sources.jar",
          "url": "crux-system-0.8.0-sources.jar",
          "size": 4117,
          "sha512": "717cbf30b8458f59d2a6dcb4ccb179af786b734a26689ac403e357ad7f73646d863884a8424ffae250a3433a5e4614903f9e21220bbd05eacd40e0130712e4d5",
          "sha256": "5f6078892d9239dd29395132cc8385d76191dbe29bc84839572dc29291a47b8b",
          "sha1": "51ba4cd7943ef1bbaf6e95b1a745f8533c38e491",
          "md5": "444f8f6c5a7f9a1b41a44724b7eccee8"
        }
      ]
    }
  ]
}
