{
  "formatVersion": "1.1",
  "component": {
    "group": "org.crux",
    "module": "crux-lib",
    "version": "0.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "crux-lib-0.6.0.jar",
          "url": "crux-lib-0.6.0.jar",
          "size": 33977,
          "sha512": "f5486ae1fe32fff619ebf7bfee2bb37c4229fa1e695beabf1639e3fb779091bdb8a032d5af274c33e1afa0282f8c726378fb896a861393440851ee50532e0a36",
          "sha256": "0c98f127ce96599db3dd39e8ff989e49e18085cb0f0727ba1462a8c6c15484ff",
          "sha1": "7293fee9e60b40bfbf55d0db18bc4e5dfd7231b5",
          "md5": "e1a81c5ed473587baa489cb135928fab"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "crux-lib-0.6.0.jar",
          "url": "crux-lib-0.6.0.jar",
          "size": 33977,
          "sha512": "f5486ae1fe32fff619ebf7bfee2bb37c4229fa1e695beabf1639e3fb779091bdb8a032d5af274c33e1afa0282f8c726378fb896a861393440851ee50532e0a36",
          "sha256": "0c98f127ce96599db3dd39e8ff989e49e18085cb0f0727ba1462a8c6c15484ff",
          "sha1": "7293fee9e60b40bfbf55d0db18bc4e5dfd7231b5",
          "md5": "e1a81c5ed473587baa489cb135928fab"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "crux-lib-0.6.0-sources.jar",
          "url": "crux-lib-0.6.0-sources.jar",
          "size": 8246,
          "sha512": "c08b7b087f671840a4a8c5f302b3da96105d8832e4c3e13de74fe7d0e4b7f545aaff990fc6c15175497722ca32287aa7df8e59873a58163b4c5f04ba5794cbf3",
          "sha256": "a198c44d63ffb63ec6661f66db8f8c6dd4ca17d22c188d25acc55df9f3b5b94a",
          "sha1": "7880d1f7f64384969fd3bd736f2c855af0f271fc",
          "md5": "7c6659cbf2b017b0c161806a306b016f"
        }
      ]
    }
  ]
}
