{
  "formatVersion": "1.1",
  "component": {
    "group": "org.crux",
    "module": "crux-lib",
    "version": "0.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "crux-lib-0.5.0.jar",
          "url": "crux-lib-0.5.0.jar",
          "size": 30144,
          "sha512": "7ecc74b22e6f71eb67ecc4ebb0eae575eca0db79cf9803ba2aac2c2589135c2352c8be817889d2fd5b36c53aebb572682b959ba766e5fd164f63204eac9c78be",
          "sha256": "1f5aebe44abaa412ed1a6da1b376dd4c883df828d2d1765c97bbfe1963d5da4b",
          "sha1": "6ad7fce233330236768a800f127311358c124fab",
          "md5": "3880fa131bd0f577e8bd3034140ea151"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "crux-lib-0.5.0.jar",
          "url": "crux-lib-0.5.0.jar",
          "size": 30144,
          "sha512": "7ecc74b22e6f71eb67ecc4ebb0eae575eca0db79cf9803ba2aac2c2589135c2352c8be817889d2fd5b36c53aebb572682b959ba766e5fd164f63204eac9c78be",
          "sha256": "1f5aebe44abaa412ed1a6da1b376dd4c883df828d2d1765c97bbfe1963d5da4b",
          "sha1": "6ad7fce233330236768a800f127311358c124fab",
          "md5": "3880fa131bd0f577e8bd3034140ea151"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "crux-lib-0.5.0-sources.jar",
          "url": "crux-lib-0.5.0-sources.jar",
          "size": 7221,
          "sha512": "4409f628c9d9b2faa04db641d45faff5d0246fb1b486a952136fca1f194c1916cbd9100c885580b355c638137325bb89fb4d6bfde743c7a2e83b479e468c8162",
          "sha256": "cb3b28220c1dd0ce11f70548cd178bb4c2fcf189e12bc1a24f4d1ad73cb01785",
          "sha1": "c052e49fc661350af84586b8d8d7cda48b50083d",
          "md5": "855f73f7fb3917760ee3d07ac26071fa"
        }
      ]
    }
  ]
}
