{
  "formatVersion": "1.1",
  "component": {
    "group": "org.crux",
    "module": "crux-lib",
    "version": "0.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "crux-lib-0.3.0.jar",
          "url": "crux-lib-0.3.0.jar",
          "size": 16904,
          "sha512": "da179dbb97fc87c7ae811d263b096b3d3f97f66370f9af3048b6ddc5d4980191f6e54e24c0e765f332c8173bc6611389b74bd329ca4c7f393aad724cc7b41b33",
          "sha256": "5234de25095d805293154b0009aff919ece257cbf6e72b68f07551c93b3e8c09",
          "sha1": "8e2a9499e81093528a2c3505a94ee08d3b3143e7",
          "md5": "b00e0e54763ca8b2acc914e5c745b6cf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "crux-lib-0.3.0.jar",
          "url": "crux-lib-0.3.0.jar",
          "size": 16904,
          "sha512": "da179dbb97fc87c7ae811d263b096b3d3f97f66370f9af3048b6ddc5d4980191f6e54e24c0e765f332c8173bc6611389b74bd329ca4c7f393aad724cc7b41b33",
          "sha256": "5234de25095d805293154b0009aff919ece257cbf6e72b68f07551c93b3e8c09",
          "sha1": "8e2a9499e81093528a2c3505a94ee08d3b3143e7",
          "md5": "b00e0e54763ca8b2acc914e5c745b6cf"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "crux-lib-0.3.0-sources.jar",
          "url": "crux-lib-0.3.0-sources.jar",
          "size": 3556,
          "sha512": "2778f51eb991ca58e0d78d47099d3880e04e118a4efcb86f09972415aea400360c6635df8c8d2f52f43bac88c4963e99b6e986f610ec15c6ce4acc2420eeef4a",
          "sha256": "e2ca210fd59e404c97fc89371a21b5b1557697dd29cae7015ad11af464e28adf",
          "sha1": "5b803d7cf71729d75006e3bc5212a37bf1852c04",
          "md5": "c18f5f42084f2cda48952003e227f3bc"
        }
      ]
    }
  ]
}
