{
  "formatVersion": "1.1",
  "component": {
    "group": "CruxLib",
    "module": "crux-processor",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "crux-processor-unspecified.jar",
          "url": "crux-processor-unspecified.jar",
          "size": 3068,
          "sha512": "9ddd750a64967bfe7ea6cd367073a600e077283b9985c8ff0685c965e6fb3e9ca34d48e0ddb2d84d3b3b1e30794441b0831515efa9a0c6a0af3df4e66823d09b",
          "sha256": "7c1de49350efe34a3ba6fe5b09b0f351d5da7276ab507dbdc99dadfa3f8a2afe",
          "sha1": "ceef28fac1e762abeaef58e7ca87a531903d9381",
          "md5": "a08f93243f98751261b898c30f41e905"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "crux-processor-unspecified.jar",
          "url": "crux-processor-unspecified.jar",
          "size": 3068,
          "sha512": "9ddd750a64967bfe7ea6cd367073a600e077283b9985c8ff0685c965e6fb3e9ca34d48e0ddb2d84d3b3b1e30794441b0831515efa9a0c6a0af3df4e66823d09b",
          "sha256": "7c1de49350efe34a3ba6fe5b09b0f351d5da7276ab507dbdc99dadfa3f8a2afe",
          "sha1": "ceef28fac1e762abeaef58e7ca87a531903d9381",
          "md5": "a08f93243f98751261b898c30f41e905"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "crux-processor-unspecified-sources.jar",
          "url": "crux-processor-unspecified-sources.jar",
          "size": 1811,
          "sha512": "69d91d8ab172a83725764955db53d31a4a5cd2ba5279c44e0a4da5cc247adfb120d20d4540ffe9e140eff08c14b5013b063bc30ddf7da5fa63e574038ccf25fc",
          "sha256": "1b45f7e71950f7b9c6471a1b803a8cff964b7ec8662ed1c180bb76adefb74f3a",
          "sha1": "fccbc70c347c0730260d55d091d16ed1249d1670",
          "md5": "900498d018bbb34d4f28ebfde004d563"
        }
      ]
    }
  ]
}
